<?php

/**
 * Implements hook_views_api().
 */
function oxfam_volunteer_views_api() {
  return array('api' => 3.0);
}

function oxfam_volunteer_disable() {
	$node_id = variable_get('oxfam_volunteer_webform_node_id', 0);
	if ($node_id > 0) {
		node_delete($node_id);
	}
}

function oxfam_volunteer_enable() {
	$node = new stdClass();
	$node->type = 'webform';
	node_object_prepare($node);
	$node->title = 'Volunteer';
	$node->language = 'und';
	$node->body[LANGUAGE_NONE][0]['value']   = '';
	$node->body[LANGUAGE_NONE][0]['format']  = 'full_html';
	$node->uid = 1;
	$node->promote = 0;
	$node->comment = 0;

	$components = array (
		  array (
		    'pid' => '0',
		    'form_key' => 'civicrm_1_contact_1_contact_contact_id',
		    'name' => 'Contact ID',
		    'type' => 'hidden',
		    'value' => '',
		    'extra' => 
		    array (
		      'private' => 0,
		      'hidden_type' => 'value',
		      'analysis' => false,
		    ),
		    'required' => '0',
		    'weight' => '2',
		    'page_num' => 1,
		  ),
		  array (
		    'pid' => '0',
		    'form_key' => 'civicrm_1_contact_1_contact_existing',
		    'name' => 'Existing Contact',
		    'type' => 'civicrm_contact',
		    'value' => '',
		    'extra' => 
		    array (
		      'allow_create' => 1,
		      'private' => 0,
		      'wrapper_classes' => '',
		      'css_classes' => '',
		      'widget' => 'hidden',
		      'search_prompt' => '- Choose existing contact -',
		      'none_prompt' => '+ Create new contact +',
		      'results_display' => 
		      array (
		        'display_name' => 'display_name',
		      ),
		      'show_hidden_contact' => '1',
		      'hide_fields' => 
		      array (
		        '' => '',
		      ),
		      'filters' => 
		      array (
		        'contact_sub_type' => '0',
		        'group' => 
		        array (
		        ),
		        'tag' => 
		        array (
		        ),
		        'check_permissions' => 1,
		      ),
		      'unique' => 0,
		      'title_display' => 'before',
		      'randomize' => 0,
		      'description' => '',
		      'attributes' => 
		      array (
		      ),
		      'default' => '',
		      'default_contact_id' => '',
		      'default_relationship' => '',
		      'dupes_allowed' => false,
		    ),
		    'required' => '0',
		    'weight' => '3',
		    'page_num' => 1,
		  ),
		  array (
		    'pid' => '0',
		    'form_key' => 'civicrm_1_contact_1_cg1_custom_8',
		    'name' => 'beschikbaarheid',
		    'type' => 'textfield',
		    'value' => '',
		    'extra' => 
		    array (
		      'description' => '',
		      'width' => 20,
		      'private' => 0,
		      'maxlength' => '',
		      'field_prefix' => '',
		      'field_suffix' => '',
		      'disabled' => 0,
		      'unique' => 0,
		      'title_display' => 0,
		      'placeholder' => '',
		      'attributes' => 
		      array (
		      ),
		      'analysis' => false,
		    ),
		    'required' => '0',
		    'weight' => '4',
		    'page_num' => 1,
		  ),
		  array (
		    'pid' => '0',
		    'form_key' => 'civicrm_1_contact_1_phone_phone',
		    'name' => 'Phone Number',
		    'type' => 'textfield',
		    'value' => '',
		    'extra' => 
		    array (
		      'width' => 20,
		      'private' => 0,
		      'maxlength' => '',
		      'field_prefix' => '',
		      'field_suffix' => '',
		      'disabled' => 0,
		      'unique' => 0,
		      'title_display' => 0,
		      'description' => '',
		      'placeholder' => '',
		      'attributes' => 
		      array (
		      ),
		      'analysis' => false,
		    ),
		    'required' => '0',
		    'weight' => '5',
		    'page_num' => 1,
		  ),
		  array (
		    'pid' => '0',
		    'form_key' => 'civicrm_1_contact_1_address_street_address',
		    'name' => 'Street Address',
		    'type' => 'textfield',
		    'value' => '',
		    'extra' => 
		    array (
		      'width' => 60,
		      'private' => 0,
		      'maxlength' => '',
		      'field_prefix' => '',
		      'field_suffix' => '',
		      'disabled' => 0,
		      'unique' => 0,
		      'title_display' => 0,
		      'description' => '',
		      'placeholder' => '',
		      'attributes' => 
		      array (
		      ),
		      'analysis' => false,
		    ),
		    'required' => '0',
		    'weight' => '6',
		    'page_num' => 1,
		  ),
		  array (
		    'pid' => '0',
		    'form_key' => 'civicrm_1_contact_1_address_supplemental_address_1',
		    'name' => 'Street Address Line 2',
		    'type' => 'textfield',
		    'value' => '',
		    'extra' => 
		    array (
		      'width' => 60,
		      'private' => 0,
		      'maxlength' => '',
		      'field_prefix' => '',
		      'field_suffix' => '',
		      'disabled' => 0,
		      'unique' => 0,
		      'title_display' => 0,
		      'description' => '',
		      'placeholder' => '',
		      'attributes' => 
		      array (
		      ),
		      'analysis' => false,
		    ),
		    'required' => '0',
		    'weight' => '7',
		    'page_num' => 1,
		  ),
		  array (
		    'pid' => '0',
		    'form_key' => 'civicrm_1_contact_1_address_city',
		    'name' => 'City',
		    'type' => 'textfield',
		    'value' => '',
		    'extra' => 
		    array (
		      'width' => 20,
		      'private' => 0,
		      'maxlength' => '',
		      'field_prefix' => '',
		      'field_suffix' => '',
		      'disabled' => 0,
		      'unique' => 0,
		      'title_display' => 0,
		      'description' => '',
		      'placeholder' => '',
		      'attributes' => 
		      array (
		      ),
		      'analysis' => false,
		    ),
		    'required' => '0',
		    'weight' => '8',
		    'page_num' => 1,
		  ),
		  array (
		    'pid' => '0',
		    'form_key' => 'civicrm_1_contact_1_address_postal_code',
		    'name' => 'Postal Code',
		    'type' => 'textfield',
		    'value' => '',
		    'extra' => 
		    array (
		      'width' => 7,
		      'private' => 0,
		      'maxlength' => '',
		      'field_prefix' => '',
		      'field_suffix' => '',
		      'disabled' => 0,
		      'unique' => 0,
		      'title_display' => 0,
		      'description' => '',
		      'placeholder' => '',
		      'attributes' => 
		      array (
		      ),
		      'analysis' => false,
		    ),
		    'required' => '0',
		    'weight' => '9',
		    'page_num' => 1,
		  ),
		  array (
		    'pid' => '0',
		    'form_key' => 'civicrm_1_contact_1_email_email',
		    'name' => 'E-mail',
		    'type' => 'email',
		    'value' => '',
		    'extra' => 
		    array (
		      'width' => 20,
		      'private' => 0,
		      'unique' => 0,
		      'disabled' => 0,
		      'title_display' => 0,
		      'description' => '',
		      'placeholder' => '',
		      'attributes' => 
		      array (
		      ),
		      'analysis' => false,
		    ),
		    'required' => '0',
		    'weight' => '10',
		    'page_num' => 1,
		  ),
		  array (
		    'pid' => '0',
		    'form_key' => 'civicrm_2_contact_1_relationship_custom_21',
		    'name' => 'Relationship to Volunteer taak in winkel',
		    'type' => 'select',
		    'value' => '',
		    'extra' => 
		    array (
		      'multiple' => 1,
		      'description' => '',
		      'civicrm_live_options' => 1,
		      'items' => 'responsible shop|verantwoordelijke winkel
	seller|verkoper (m/v)
	advisor textile|adviseur (m/v) textiel
	advisor bookshop|adviseur (m/v) bookshop
	advisor ict|adviseur (m/v) ICT
	sorter|sorteerder (m/v)
	public relations collaborator|public relations medewerk(st)er
	north south collaborator|Noord-Zuid medewerk(st)er
	finance and administration collaborator|financies en administratie medewerk(st)er',
		      'private' => 0,
		      'aslist' => NULL,
		      'optrand' => 0,
		      'other_option' => NULL,
		      'other_text' => 'Other...',
		      'title_display' => 0,
		      'custom_keys' => false,
		      'options_source' => '',
		      'analysis' => true,
		    ),
		    'required' => '0',
		    'weight' => '11',
		    'page_num' => 1,
		  ),
		  array (
		    'pid' => '0',
		    'form_key' => 'civicrm_2_contact_1_contact_existing',
		    'name' => 'Existing Contact',
		    'type' => 'civicrm_contact',
		    'value' => '',
		    'extra' => 
		    array (
		      'allow_create' => 0,
		      'private' => 0,
		      'wrapper_classes' => '',
		      'css_classes' => '',
		      'widget' => 'hidden',
		      'search_prompt' => '- Choose existing contact -',
		      'none_prompt' => '- None Found -',
		      'results_display' => 
		      array (
		        'display_name' => 'display_name',
		      ),
		      'show_hidden_contact' => '0',
		      'default' => 'relationship',
		      'default_relationship' => 
		      array (
		        '5_b' => '5_b',
		      ),
		      'dupes_allowed' => 0,
		      'filters' => 
		      array (
		        'contact_sub_type' => '0',
		        'group' => 
		        array (
		        ),
		        'tag' => 
		        array (
		        ),
		        'check_permissions' => 0,
		      ),
		      'unique' => 0,
		      'title_display' => 'before',
		      'randomize' => 0,
		      'description' => '',
		      'hide_fields' => 
		      array (
		      ),
		      'attributes' => 
		      array (
		      ),
		      'default_contact_id' => '',
		    ),
		    'required' => '0',
		    'weight' => '61',
		    'page_num' => 1,
		  ), 
		  array (
		    'pid' => '0',
		    'form_key' => 'civicrm_2_contact_1_contact_contact_id',
		    'name' => 'Contact ID',
		    'type' => 'hidden',
		    'value' => '',
		    'extra' => 
		    array (
		      'private' => 0,
		      'hidden_type' => 'value',
		      'analysis' => false,
		    ),
		    'required' => '0',
		    'weight' => '68',
		    'page_num' => 1,
		  ),
	);

	$node->webform = array(
		'confirmation' => '',
		'confirmation_format' => 'plain_text',
		'redirect_url' => '/volunteers',
		'status' => '1',
		'block' => '0',
		'allow_draft' => '0',
		'auto_save' => '0',
		'submit_notice' => '1',
		'submit_text' => 'Save',
		'submit_limit' => '-1',
		'submit_interval' => '-1',
		'total_submit_limit' => '-1',
		'total_submit_interval' => '-1',
		'progressbar_bar' => '0',
		'progressbar_page_number' => '0',
		'progressbar_percent' => '0',
		'progressbar_pagebreak_labels' => '0',
		'progressbar_include_confirmation' => '1',
		'progressbar_label_first' => 'Start',
		'progressbar_label_confirmation' => 'Complete',
		'record_exists' => true,
		'roles' => 
		array (
		  0 => '5',
		),
		'emails' => array(),
		'components' => $components,
	);


	$webform_civicrm_data = array (
		'contact' => array (
			1 => array (
				'contact' => array(
					1 => array (
						'contact_type' => 'individual',
						'contact_sub_type' => array(
							'Volunteer' => 'Volunteer'
						),
						'webform_label' => 'Volunteer',
					),
				),
				'number_of_cg1' => 1,
				'number_of_other' => 0,
				'number_of_address' => 1,
				'number_of_phone' => 1,
				'number_of_email' => 1,
				'number_of_website' => 0,
				'address' => array (
					1 => array(
						'location_type_id' => 1,
					)
				),
				'phone' => array (
					1 => array(
						'phone_type_id' => 1,
						'location_type_id' => 1
					)
				),
				'email' => array(
					1 => array (
						'location_type_id' => 1
					)
				)
			),
			2 => array (
				'contact' => array (
					1 => array (
						'contact_type' => 'organization',
						'contact_sub_type' => array (),
						'webform_label' => 'Shop'
					)
				),
				'number_of_other' => 0,
				'number_of_address' => 0,
				'number_of_phone' => 0,
				'number_of_email' => 0,
				'number_of_website' => 0,
				'number_of_relationship' => 1,
				'relationship' => array (
					1 => array(
						'relationship_type_id' => array (
							'5_b' => '5_b'
						),
						'is_active' => 1
					)
				)
			)
		),
		'membership' => array( 
			1 => array ( 'number_of_membership' => 0 ),
			2 => array ( 'number_of_membership' => 0 ),
		),
		'participant_reg_type' => 0,
		'reg_options' => array (
			'event_type' => 'any',
			'show_past_events' => 0,
			'title_display' => 'title',
			'show_remaining' => 0,
			'validate' => 1,
			'block_form' => 0,
		)
	);

	$node->path = array('alias' => 'volunteers/edit');
	// Save the node.
	node_save($node);

	$node_id = $node->nid;
	variable_set('oxfam_volunteer_webform_node_id', $node_id);

	//set civicrm settings
	$civicrm_settings = new stdClass();
	$civicrm_settings->nid = $node_id;
	$civicrm_settings->data = $webform_civicrm_data;
	$civicrm_settings->prefix_known = '';
	$civicrm_settings->prefix_unknown = '';
	$civicrm_settings->message = '';
	$civicrm_settings->confirm_subscription = 1;
	$civicrm_settings->block_unknown_users = 1;
	$civicrm_settings->create_fieldsets = 0;
	$civicrm_settings->new_contact_source = 'Shop manager';
	drupal_write_record('webform_civicrm_forms', $civicrm_settings);
}

/**
 * Implements hook_views_default_views().
 */
function oxfam_volunteer_views_default_views() {
$view = new view();
	$view->name = 'volunteers';
	$view->description = '';
	$view->tag = 'oxfam';
	$view->base_table = 'civicrm_contact';
	$view->human_name = 'Volunteers';
	$view->core = 7;
	$view->api_version = '3.0';
	$view->disabled = FALSE; /* Edit this to true to make a default view disabled initially */

  /* Display: Master */
  $handler = $view->new_display('default', 'Master', 'default');
  $handler->display->display_options['title'] = 'Volunteers';
  $handler->display->display_options['use_more_always'] = FALSE;
  $handler->display->display_options['access']['type'] = 'none';
  $handler->display->display_options['cache']['type'] = 'none';
  $handler->display->display_options['query']['type'] = 'views_query';
  $handler->display->display_options['exposed_form']['type'] = 'basic';
  $handler->display->display_options['exposed_form']['options']['reset_button_label'] = 'Opnieuw instellen';
  $handler->display->display_options['pager']['type'] = 'full';
  $handler->display->display_options['pager']['options']['items_per_page'] = '10';
  $handler->display->display_options['pager']['options']['tags']['first'] = '« eerste';
  $handler->display->display_options['pager']['options']['tags']['previous'] = '‹ vorige';
  $handler->display->display_options['pager']['options']['tags']['next'] = 'volgende ›';
  $handler->display->display_options['pager']['options']['tags']['last'] = 'laatste »';
  $handler->display->display_options['style_plugin'] = 'table';
  $handler->display->display_options['style_options']['columns'] = array(
    'id' => 'id',
    'display_name' => 'display_name',
  );
  $handler->display->display_options['style_options']['default'] = '-1';
  $handler->display->display_options['style_options']['info'] = array(
    'id' => array(
      'sortable' => 0,
      'default_sort_order' => 'asc',
      'align' => '',
      'separator' => '',
      'empty_column' => 0,
    ),
    'display_name' => array(
      'sortable' => 0,
      'default_sort_order' => 'asc',
      'align' => '',
      'separator' => '',
      'empty_column' => 0,
    ),
  );
  /* Relationship: CiviCRM Contacts: CiviCRM Relationship (starting from contact A) */
  $handler->display->display_options['relationships']['relationship_id_a']['id'] = 'relationship_id_a';
  $handler->display->display_options['relationships']['relationship_id_a']['table'] = 'civicrm_contact';
  $handler->display->display_options['relationships']['relationship_id_a']['field'] = 'relationship_id_a';
  $handler->display->display_options['relationships']['relationship_id_a']['label'] = 'volunteer_for';
  $handler->display->display_options['relationships']['relationship_id_a']['required'] = TRUE;
  $handler->display->display_options['relationships']['relationship_id_a']['relationship_type'] = '5';
  /* Relationship: CiviCRM Relationships: Contact ID B */
  $handler->display->display_options['relationships']['contact_id_b_']['id'] = 'contact_id_b_';
  $handler->display->display_options['relationships']['contact_id_b_']['table'] = 'civicrm_relationship';
  $handler->display->display_options['relationships']['contact_id_b_']['field'] = 'contact_id_b_';
  $handler->display->display_options['relationships']['contact_id_b_']['relationship'] = 'relationship_id_a';
  $handler->display->display_options['relationships']['contact_id_b_']['label'] = 'shop';
  $handler->display->display_options['relationships']['contact_id_b_']['required'] = TRUE;
  /* Relationship: CiviCRM Contacts: CiviCRM Relationship (starting from Contact B) */
  $handler->display->display_options['relationships']['relationship_id_b']['id'] = 'relationship_id_b';
  $handler->display->display_options['relationships']['relationship_id_b']['table'] = 'civicrm_contact';
  $handler->display->display_options['relationships']['relationship_id_b']['field'] = 'relationship_id_b';
  $handler->display->display_options['relationships']['relationship_id_b']['relationship'] = 'contact_id_b_';
  $handler->display->display_options['relationships']['relationship_id_b']['label'] = 'manager_of';
  $handler->display->display_options['relationships']['relationship_id_b']['required'] = TRUE;
  $handler->display->display_options['relationships']['relationship_id_b']['relationship_type'] = '15';
  /* Relationship: CiviCRM Relationships: Contact ID A */
  $handler->display->display_options['relationships']['contact_id_a_']['id'] = 'contact_id_a_';
  $handler->display->display_options['relationships']['contact_id_a_']['table'] = 'civicrm_relationship';
  $handler->display->display_options['relationships']['contact_id_a_']['field'] = 'contact_id_a_';
  $handler->display->display_options['relationships']['contact_id_a_']['relationship'] = 'relationship_id_b';
  $handler->display->display_options['relationships']['contact_id_a_']['label'] = 'manager';
  $handler->display->display_options['relationships']['contact_id_a_']['required'] = TRUE;
  /* Relationship: CiviCRM Contacts: Drupal ID */
  $handler->display->display_options['relationships']['drupal_id']['id'] = 'drupal_id';
  $handler->display->display_options['relationships']['drupal_id']['table'] = 'civicrm_contact';
  $handler->display->display_options['relationships']['drupal_id']['field'] = 'drupal_id';
  $handler->display->display_options['relationships']['drupal_id']['relationship'] = 'contact_id_a_';
  $handler->display->display_options['relationships']['drupal_id']['label'] = 'user';
  $handler->display->display_options['relationships']['drupal_id']['required'] = TRUE;
	/* Veld: CiviCRM Contacts: Contact ID */
	$handler->display->display_options['fields']['id']['id'] = 'id';
	$handler->display->display_options['fields']['id']['table'] = 'civicrm_contact';
	$handler->display->display_options['fields']['id']['field'] = 'id';
	$handler->display->display_options['fields']['id']['label'] = '';
	$handler->display->display_options['fields']['id']['exclude'] = TRUE;
	$handler->display->display_options['fields']['id']['element_label_colon'] = FALSE;
	/* Veld: Shop ID */
	$handler->display->display_options['fields']['id_1']['id'] = 'id_1';
	$handler->display->display_options['fields']['id_1']['table'] = 'civicrm_contact';
	$handler->display->display_options['fields']['id_1']['field'] = 'id';
	$handler->display->display_options['fields']['id_1']['relationship'] = 'contact_id_b_';
	$handler->display->display_options['fields']['id_1']['ui_name'] = 'Shop ID';
	$handler->display->display_options['fields']['id_1']['label'] = '';
	$handler->display->display_options['fields']['id_1']['exclude'] = TRUE;
	$handler->display->display_options['fields']['id_1']['element_label_colon'] = FALSE;
	/* Veld: CiviCRM Contacts: Display Name */
	$handler->display->display_options['fields']['display_name_1']['id'] = 'display_name_1';
	$handler->display->display_options['fields']['display_name_1']['table'] = 'civicrm_contact';
	$handler->display->display_options['fields']['display_name_1']['field'] = 'display_name';
	$handler->display->display_options['fields']['display_name_1']['label'] = 'Vrijwilliger';
	$handler->display->display_options['fields']['display_name_1']['alter']['make_link'] = TRUE;
	$handler->display->display_options['fields']['display_name_1']['alter']['path'] = 'volunteers/edit?cid1=[id]&cid2=[id_1]';
	$handler->display->display_options['fields']['display_name_1']['link_to_civicrm_contact'] = 0;
  /* Veld: CiviCRM Address: Full Street Address */
  $handler->display->display_options['fields']['street_address']['id'] = 'street_address';
  $handler->display->display_options['fields']['street_address']['table'] = 'civicrm_address';
  $handler->display->display_options['fields']['street_address']['field'] = 'street_address';
  $handler->display->display_options['fields']['street_address']['location_type'] = '0';
  $handler->display->display_options['fields']['street_address']['location_op'] = '0';
  $handler->display->display_options['fields']['street_address']['is_primary'] = 1;
  $handler->display->display_options['fields']['street_address']['is_billing'] = 0;
  /* Veld: CiviCRM Address: ZIP / Postal Code */
  $handler->display->display_options['fields']['postal_code']['id'] = 'postal_code';
  $handler->display->display_options['fields']['postal_code']['table'] = 'civicrm_address';
  $handler->display->display_options['fields']['postal_code']['field'] = 'postal_code';
  $handler->display->display_options['fields']['postal_code']['location_type'] = '0';
  $handler->display->display_options['fields']['postal_code']['location_op'] = '0';
  $handler->display->display_options['fields']['postal_code']['is_primary'] = 1;
  $handler->display->display_options['fields']['postal_code']['is_billing'] = 0;
  /* Veld: CiviCRM Address: City / Suburb */
  $handler->display->display_options['fields']['city']['id'] = 'city';
  $handler->display->display_options['fields']['city']['table'] = 'civicrm_address';
  $handler->display->display_options['fields']['city']['field'] = 'city';
  $handler->display->display_options['fields']['city']['location_type'] = '0';
  $handler->display->display_options['fields']['city']['location_op'] = '0';
  $handler->display->display_options['fields']['city']['is_primary'] = 1;
  $handler->display->display_options['fields']['city']['is_billing'] = 0;
  /* Veld: CiviCRM Phone Details: Phone Number */
  $handler->display->display_options['fields']['phone']['id'] = 'phone';
  $handler->display->display_options['fields']['phone']['table'] = 'civicrm_phone';
  $handler->display->display_options['fields']['phone']['field'] = 'phone';
  $handler->display->display_options['fields']['phone']['location_type'] = '0';
  $handler->display->display_options['fields']['phone']['location_op'] = '0';
  $handler->display->display_options['fields']['phone']['is_primary'] = 1;
  $handler->display->display_options['fields']['phone']['phone_type'] = '0';
  /* Veld: CiviCRM Email: Email Address */
  $handler->display->display_options['fields']['email']['id'] = 'email';
  $handler->display->display_options['fields']['email']['table'] = 'civicrm_email';
  $handler->display->display_options['fields']['email']['field'] = 'email';
  $handler->display->display_options['fields']['email']['location_type'] = '0';
  $handler->display->display_options['fields']['email']['location_op'] = '0';
  $handler->display->display_options['fields']['email']['is_primary'] = 1;
  /* Veld: CiviCRM Custom: Oxfam volunteer: taak in winkel */
  $handler->display->display_options['fields']['task_shop_21']['id'] = 'task_shop_21';
  $handler->display->display_options['fields']['task_shop_21']['table'] = 'civicrm_value_oxfam_volunteer_5';
  $handler->display->display_options['fields']['task_shop_21']['field'] = 'task_shop_21';
  /* Veld: CiviCRM Custom: Oxfam medewerker Details: beschikbaarheid */
  $handler->display->display_options['fields']['availabilit__8']['id'] = 'availabilit__8';
  $handler->display->display_options['fields']['availabilit__8']['table'] = 'civicrm_value_oxfam_volunteer_details_1';
  $handler->display->display_options['fields']['availabilit__8']['field'] = 'availabilit__8';
  /* Filter criterion: Gebruiker: Current */
  $handler->display->display_options['filters']['uid_current']['id'] = 'uid_current';
  $handler->display->display_options['filters']['uid_current']['table'] = 'users';
  $handler->display->display_options['filters']['uid_current']['field'] = 'uid_current';
  $handler->display->display_options['filters']['uid_current']['relationship'] = 'drupal_id';
  $handler->display->display_options['filters']['uid_current']['value'] = '1';

  /* Display: Page */
  $handler = $view->new_display('page', 'Page', 'page');
  $handler->display->display_options['defaults']['hide_admin_links'] = FALSE;
  $handler->display->display_options['path'] = 'volunteers';
  $translatables['test'] = array(
    t('Master'),
    t('Volunteers'),
    t('more'),
    t('Apply'),
    t('Opnieuw instellen'),
    t('Sort by'),
    t('Asc'),
    t('Desc'),
    t('Items per page'),
    t('- All -'),
    t('Offset'),
    t('« eerste'),
    t('‹ vorige'),
    t('volgende ›'),
    t('laatste »'),
    t('volunteer_for'),
    t('shop'),
    t('manager_of'),
    t('manager'),
    t('user'),
    t('Vrijwilliger'),
    t('Full Street Address'),
    t('ZIP / Postal Code'),
    t('City / Suburb'),
    t('Phone Number'),
    t('Email Address'),
    t('taak in winkel'),
    t('beschikbaarheid'),
    t('Page'),
  );

  $views[$view->name] = $view;
// return views
  return $views;
}
