<?php

/**
 * Implements hook_views_api().
 */
function oxfam_volunteer_views_api() {
  return array('api' => 3.0);
}

function oxfam_volunteer_disable() {
	$node_id = variable_get('oxfam_volunteer_webform_node_id', 0);
	if ($node_id > 0) {
		node_delete($node_id);
	}
}

function oxfam_volunteer_enable() {
	$node = new stdClass();
	$node->type = 'webform';
	node_object_prepare($node);
	$node->title = 'Volunteer';
	$node->language = 'und';
	$node->body[LANGUAGE_NONE][0]['value']   = '';
	$node->body[LANGUAGE_NONE][0]['format']  = 'full_html';
	$node->uid = 1;
	$node->promote = 0;
	$node->comment = 0;

	$components = array (
		  1 => array (
		    'pid' => '0',
		    'form_key' => 'civicrm_1_contact_1_contact_contact_id',
		    'name' => 'Contact ID',
		    'type' => 'hidden',
		    'value' => '',
		    'extra' => 
		    array (
		      'private' => 0,
		      'hidden_type' => 'value',
		      'analysis' => false,
		    ),
		    'required' => '0',
		    'weight' => '2',
		    'page_num' => 1,
		  ),
		  2 => array (
		    'pid' => '0',
		    'form_key' => 'civicrm_1_contact_1_contact_existing',
		    'name' => 'Existing Contact',
		    'type' => 'civicrm_contact',
		    'value' => '',
		    'extra' => 
		    array (
		      'allow_create' => 1,
		      'private' => 0,
		      'wrapper_classes' => '',
		      'css_classes' => '',
		      'widget' => 'hidden',
		      'search_prompt' => '- Choose existing contact -',
		      'none_prompt' => '+ Create new contact +',
		      'results_display' => 
		      array (
		        'display_name' => 'display_name',
		      ),
		      'show_hidden_contact' => '1',
		      'hide_fields' => 
		      array (
		        '' => '',
		      ),
		      'filters' => 
		      array (
		        'contact_sub_type' => '0',
		        'group' => 
		        array (
		        ),
		        'tag' => 
		        array (
		        ),
		        'check_permissions' => 1,
		      ),
		      'unique' => 0,
		      'title_display' => 'before',
		      'randomize' => 0,
		      'description' => '',
		      'attributes' => 
		      array (
		      ),
		      'default' => '',
		      'default_contact_id' => '',
		      'default_relationship' => '',
		      'dupes_allowed' => false,
		    ),
		    'required' => '0',
		    'weight' => '3',
		    'page_num' => 1,
		  ),
		  3=> array (
		    'pid' => '0',
		    'form_key' => 'civicrm_1_contact_1_cg1_custom_8',
		    'name' => 'beschikbaarheid',
		    'type' => 'textfield',
		    'value' => '',
		    'extra' => 
		    array (
		      'description' => '',
		      'width' => 20,
		      'private' => 0,
		      'maxlength' => '',
		      'field_prefix' => '',
		      'field_suffix' => '',
		      'disabled' => 0,
		      'unique' => 0,
		      'title_display' => 0,
		      'placeholder' => '',
		      'attributes' => 
		      array (
		      ),
		      'analysis' => false,
		    ),
		    'required' => '0',
		    'weight' => '4',
		    'page_num' => 1,
		  ),
		  4 => array (
		    'pid' => '0',
		    'form_key' => 'civicrm_1_contact_1_phone_phone',
		    'name' => 'Phone Number',
		    'type' => 'textfield',
		    'value' => '',
		    'extra' => 
		    array (
		      'width' => 20,
		      'private' => 0,
		      'maxlength' => '',
		      'field_prefix' => '',
		      'field_suffix' => '',
		      'disabled' => 0,
		      'unique' => 0,
		      'title_display' => 0,
		      'description' => '',
		      'placeholder' => '',
		      'attributes' => 
		      array (
		      ),
		      'analysis' => false,
		    ),
		    'required' => '0',
		    'weight' => '5',
		    'page_num' => 1,
		  ),
		  5 => array (
		    'pid' => '0',
		    'form_key' => 'civicrm_1_contact_1_address_street_address',
		    'name' => 'Street Address',
		    'type' => 'textfield',
		    'value' => '',
		    'extra' => 
		    array (
		      'width' => 60,
		      'private' => 0,
		      'maxlength' => '',
		      'field_prefix' => '',
		      'field_suffix' => '',
		      'disabled' => 0,
		      'unique' => 0,
		      'title_display' => 0,
		      'description' => '',
		      'placeholder' => '',
		      'attributes' => 
		      array (
		      ),
		      'analysis' => false,
		    ),
		    'required' => '0',
		    'weight' => '6',
		    'page_num' => 1,
		  ),
		  6 => array (
		    'pid' => '0',
		    'form_key' => 'civicrm_1_contact_1_address_supplemental_address_1',
		    'name' => 'Street Address Line 2',
		    'type' => 'textfield',
		    'value' => '',
		    'extra' => 
		    array (
		      'width' => 60,
		      'private' => 0,
		      'maxlength' => '',
		      'field_prefix' => '',
		      'field_suffix' => '',
		      'disabled' => 0,
		      'unique' => 0,
		      'title_display' => 0,
		      'description' => '',
		      'placeholder' => '',
		      'attributes' => 
		      array (
		      ),
		      'analysis' => false,
		    ),
		    'required' => '0',
		    'weight' => '7',
		    'page_num' => 1,
		  ),
		 7 =>  array (
		    'pid' => '0',
		    'form_key' => 'civicrm_1_contact_1_address_city',
		    'name' => 'City',
		    'type' => 'textfield',
		    'value' => '',
		    'extra' => 
		    array (
		      'width' => 20,
		      'private' => 0,
		      'maxlength' => '',
		      'field_prefix' => '',
		      'field_suffix' => '',
		      'disabled' => 0,
		      'unique' => 0,
		      'title_display' => 0,
		      'description' => '',
		      'placeholder' => '',
		      'attributes' => 
		      array (
		      ),
		      'analysis' => false,
		    ),
		    'required' => '0',
		    'weight' => '8',
		    'page_num' => 1,
		  ),
		  8 => array (
		    'pid' => '0',
		    'form_key' => 'civicrm_1_contact_1_address_postal_code',
		    'name' => 'Postal Code',
		    'type' => 'textfield',
		    'value' => '',
		    'extra' => 
		    array (
		      'width' => 7,
		      'private' => 0,
		      'maxlength' => '',
		      'field_prefix' => '',
		      'field_suffix' => '',
		      'disabled' => 0,
		      'unique' => 0,
		      'title_display' => 0,
		      'description' => '',
		      'placeholder' => '',
		      'attributes' => 
		      array (
		      ),
		      'analysis' => false,
		    ),
		    'required' => '0',
		    'weight' => '9',
		    'page_num' => 1,
		  ),
		  9 => array (
		    'pid' => '0',
		    'form_key' => 'civicrm_1_contact_1_email_email',
		    'name' => 'E-mail',
		    'type' => 'email',
		    'value' => '',
		    'extra' => 
		    array (
		      'width' => 20,
		      'private' => 0,
		      'unique' => 0,
		      'disabled' => 0,
		      'title_display' => 0,
		      'description' => '',
		      'placeholder' => '',
		      'attributes' => 
		      array (
		      ),
		      'analysis' => false,
		    ),
		    'required' => '0',
		    'weight' => '10',
		    'page_num' => 1,
		  ),
		  10 => array (
		    'pid' => '0',
		    'form_key' => 'civicrm_2_contact_1_relationship_custom_21',
		    'name' => 'Taak in winkel',
		    'type' => 'select',
		    'value' => '',
		    'extra' => 
		    array (
		      'multiple' => 1,
		      'description' => '',
		      'civicrm_live_options' => 1,
		      'items' => 'responsible shop|verantwoordelijke winkel
	seller|verkoper (m/v)
	advisor textile|adviseur (m/v) textiel
	advisor bookshop|adviseur (m/v) bookshop
	advisor ict|adviseur (m/v) ICT
	sorter|sorteerder (m/v)
	public relations collaborator|public relations medewerk(st)er
	north south collaborator|Noord-Zuid medewerk(st)er
	finance and administration collaborator|financies en administratie medewerk(st)er',
		      'private' => 0,
		      'aslist' => NULL,
		      'optrand' => 0,
		      'other_option' => NULL,
		      'other_text' => 'Other...',
		      'title_display' => 0,
		      'custom_keys' => false,
		      'options_source' => '',
		      'analysis' => true,
		    ),
		    'required' => '0',
		    'weight' => '11',
		    'page_num' => 1,
		  ),
		  11 => array (
		    'pid' => '0',
		    'form_key' => 'civicrm_2_contact_1_contact_existing',
		    'name' => 'Existing Contact',
		    'type' => 'civicrm_contact',
		    'value' => '',
		    'extra' => 
		    array (
		      'allow_create' => 0,
		      'private' => 0,
		      'wrapper_classes' => '',
		      'css_classes' => '',
		      'widget' => 'hidden',
		      'search_prompt' => '- Choose existing contact -',
		      'none_prompt' => '- None Found -',
		      'results_display' => 
		      array (
		        'display_name' => 'display_name',
		      ),
		      'show_hidden_contact' => '0',
		      'default' => 'relationship',
		      'default_relationship' => 
		      array (
		        '5_b' => '5_b',
		      ),
		      'dupes_allowed' => 0,
		      'filters' => 
		      array (
		        'contact_sub_type' => '0',
		        'group' => 
		        array (
		        ),
		        'tag' => 
		        array (
		        ),
		        'check_permissions' => 0,
		      ),
		      'unique' => 0,
		      'title_display' => 'before',
		      'randomize' => 0,
		      'description' => '',
		      'hide_fields' => 
		      array (
		      ),
		      'attributes' => 
		      array (
		      ),
		      'default_contact_id' => '',
		    ),
		    'required' => '0',
		    'weight' => '61',
		    'page_num' => 1,
		  ), 
		  12 => array (
		    'pid' => '0',
		    'form_key' => 'civicrm_2_contact_1_contact_contact_id',
		    'name' => 'Contact ID',
		    'type' => 'hidden',
		    'value' => '',
		    'extra' => 
		    array (
		      'private' => 0,
		      'hidden_type' => 'value',
		      'analysis' => false,
		    ),
		    'required' => '0',
		    'weight' => '68',
		    'page_num' => 1,
		  ),
			25 => 
				array (
				  'cid' => '25',
				  'pid' => '0',
				  'form_key' => 'beschikbaarheid',
				  'name' => 'Beschikbaarheid',
				  'type' => 'fieldset',
				  'value' => '',
				  'extra' => 
				  array (
				    'private' => 0,
				    'css_classes' => '',
				    'title_display' => 0,
				    'collapsible' => 0,
				    'collapsed' => 0,
				    'description' => '',
				  ),
				  'required' => '0',
				  'weight' => '14',
				  'page_num' => 1,
				),
				13 => 
				array (
				  'cid' => '13',
				  'pid' => '25',
				  'form_key' => 'civicrm_2_contact_1_relationship_custom_33',
				  'name' => 'MA ochtend',
				  'type' => 'select',
				  'value' => '0',
				  'extra' => 
				  array (
				    'items' => '1|Ja
												0|Nee',
				    'multiple' => 0,
				    'title_display' => 'inline',
				    'private' => 0,
				    'wrapper_classes' => '',
				    'css_classes' => '',
				    'aslist' => 1,
				    'civicrm_live_options' => '1',
				    'optrand' => 0,
				    'other_option' => NULL,
				    'other_text' => 'Other...',
				    'description' => '',
				    'custom_keys' => false,
				    'options_source' => '',
				    'analysis' => true,
				  ),
				  'required' => '0',
				  'weight' => '15',
				  'page_num' => 1,
				),
				14 => 
				array (
				  'cid' => '14',
				  'pid' => '25',
				  'form_key' => 'civicrm_2_contact_1_relationship_custom_34',
				  'name' => 'MA middag',
				  'type' => 'select',
				  'value' => '0',
				  'extra' => 
				  array (
				    'items' => '1|Ja
												0|Nee',
				    'multiple' => 0,
				    'title_display' => 'inline',
				    'private' => 0,
				    'wrapper_classes' => '',
				    'css_classes' => '',
				    'aslist' => 1,
				    'civicrm_live_options' => '1',
				    'optrand' => 0,
				    'other_option' => NULL,
				    'other_text' => 'Other...',
				    'description' => '',
				    'custom_keys' => false,
				    'options_source' => '',
				    'analysis' => true,
				  ),
				  'required' => '0',
				  'weight' => '16',
				  'page_num' => 1,
				),
				15 => 
				array (
				  'cid' => '15',
				  'pid' => '25',
				  'form_key' => 'civicrm_2_contact_1_relationship_custom_35',
				  'name' => 'DI ochtend',
				  'type' => 'select',
				  'value' => '0',
				  'extra' => 
				  array (
				    'items' => '1|Ja
												0|Nee',
				    'multiple' => 0,
				    'title_display' => 'inline',
				    'private' => 0,
				    'wrapper_classes' => '',
				    'css_classes' => '',
				    'aslist' => 1,
				    'civicrm_live_options' => '1',
				    'optrand' => 0,
				    'other_option' => NULL,
				    'other_text' => 'Other...',
				    'description' => '',
				    'custom_keys' => false,
				    'options_source' => '',
				    'analysis' => true,
				  ),
				  'required' => '0',
				  'weight' => '17',
				  'page_num' => 1,
				),
				16 => 
				array (
				  'cid' => '16',
				  'pid' => '25',
				  'form_key' => 'civicrm_2_contact_1_relationship_custom_36',
				  'name' => 'DI middag',
				  'type' => 'select',
				  'value' => '0',
				  'extra' => 
				  array (
				    'items' => '1|Ja
												0|Nee',
				    'multiple' => 0,
				    'title_display' => 'inline',
				    'private' => 0,
				    'wrapper_classes' => '',
				    'css_classes' => '',
				    'aslist' => 1,
				    'civicrm_live_options' => '1',
				    'optrand' => 0,
				    'other_option' => NULL,
				    'other_text' => 'Other...',
				    'description' => '',
				    'custom_keys' => false,
				    'options_source' => '',
				    'analysis' => true,
				  ),
				  'required' => '0',
				  'weight' => '18',
				  'page_num' => 1,
				),
				17 => 
				array (
				  'cid' => '17',
				  'pid' => '25',
				  'form_key' => 'civicrm_2_contact_1_relationship_custom_37',
				  'name' => 'WO ochtend',
				  'type' => 'select',
				  'value' => '0',
				  'extra' => 
				  array (
				    'items' => '1|Ja
												0|Nee',
				    'multiple' => 0,
				    'title_display' => 'inline',
				    'private' => 0,
				    'wrapper_classes' => '',
				    'css_classes' => '',
				    'aslist' => 1,
				    'civicrm_live_options' => '1',
				    'optrand' => 0,
				    'other_option' => NULL,
				    'other_text' => 'Other...',
				    'description' => '',
				    'custom_keys' => false,
				    'options_source' => '',
				    'analysis' => true,
				  ),
				  'required' => '0',
				  'weight' => '19',
				  'page_num' => 1,
				),
				18 => 
				array (
				  'cid' => '18',
				  'pid' => '25',
				  'form_key' => 'civicrm_2_contact_1_relationship_custom_38',
				  'name' => 'WO middag',
				  'type' => 'select',
				  'value' => '0',
				  'extra' => 
				  array (
				    'items' => '1|Ja
												0|Nee',
				    'multiple' => 0,
				    'title_display' => 'inline',
				    'private' => 0,
				    'wrapper_classes' => '',
				    'css_classes' => '',
				    'aslist' => 1,
				    'civicrm_live_options' => '1',
				    'optrand' => 0,
				    'other_option' => NULL,
				    'other_text' => 'Other...',
				    'description' => '',
				    'custom_keys' => false,
				    'options_source' => '',
				    'analysis' => true,
				  ),
				  'required' => '0',
				  'weight' => '20',
				  'page_num' => 1,
				),
				19 => 
				array (
				  'cid' => '19',
				  'pid' => '25',
				  'form_key' => 'civicrm_2_contact_1_relationship_custom_39',
				  'name' => 'DO ochtend',
				  'type' => 'select',
				  'value' => '0',
				  'extra' => 
				  array (
				    'items' => '1|Ja
												0|Nee',
				    'multiple' => 0,
				    'title_display' => 'inline',
				    'private' => 0,
				    'wrapper_classes' => '',
				    'css_classes' => '',
				    'aslist' => 1,
				    'civicrm_live_options' => '1',
				    'optrand' => 0,
				    'other_option' => NULL,
				    'other_text' => 'Other...',
				    'description' => '',
				    'custom_keys' => false,
				    'options_source' => '',
				    'analysis' => true,
				  ),
				  'required' => '0',
				  'weight' => '21',
				  'page_num' => 1,
				),
				20 => 
				array (
				  'cid' => '20',
				  'pid' => '25',
				  'form_key' => 'civicrm_2_contact_1_relationship_custom_40',
				  'name' => 'DO middag',
				  'type' => 'select',
				  'value' => '0',
				  'extra' => 
				  array (
				    'items' => '1|Ja
												0|Nee',
				    'multiple' => 0,
				    'title_display' => 'inline',
				    'private' => 0,
				    'wrapper_classes' => '',
				    'css_classes' => '',
				    'aslist' => 1,
				    'civicrm_live_options' => '1',
				    'optrand' => 0,
				    'other_option' => NULL,
				    'other_text' => 'Other...',
				    'description' => '',
				    'custom_keys' => false,
				    'options_source' => '',
				    'analysis' => true,
				  ),
				  'required' => '0',
				  'weight' => '22',
				  'page_num' => 1,
				),
				21 => 
				array (
				  'cid' => '21',
				  'pid' => '25',
				  'form_key' => 'civicrm_2_contact_1_relationship_custom_41',
				  'name' => 'VR ochtend',
				  'type' => 'select',
				  'value' => '0',
				  'extra' => 
				  array (
				    'items' => '1|Ja
												0|Nee',
				    'multiple' => 0,
				    'title_display' => 'inline',
				    'private' => 0,
				    'wrapper_classes' => '',
				    'css_classes' => '',
				    'aslist' => 1,
				    'civicrm_live_options' => '1',
				    'optrand' => 0,
				    'other_option' => NULL,
				    'other_text' => 'Other...',
				    'description' => '',
				    'custom_keys' => false,
				    'options_source' => '',
				    'analysis' => true,
				  ),
				  'required' => '0',
				  'weight' => '23',
				  'page_num' => 1,
				),
				22 => 
				array (
				  'cid' => '22',
				  'pid' => '25',
				  'form_key' => 'civicrm_2_contact_1_relationship_custom_42',
				  'name' => 'VR middag',
				  'type' => 'select',
				  'value' => '0',
				  'extra' => 
				  array (
				    'items' => '1|Ja
												0|Nee',
				    'multiple' => 0,
				    'title_display' => 'inline',
				    'private' => 0,
				    'wrapper_classes' => '',
				    'css_classes' => '',
				    'aslist' => 1,
				    'civicrm_live_options' => '1',
				    'optrand' => 0,
				    'other_option' => NULL,
				    'other_text' => 'Other...',
				    'description' => '',
				    'custom_keys' => false,
				    'options_source' => '',
				    'analysis' => true,
				  ),
				  'required' => '0',
				  'weight' => '24',
				  'page_num' => 1,
				),
				23 => 
				array (
				  'cid' => '23',
				  'pid' => '25',
				  'form_key' => 'civicrm_2_contact_1_relationship_custom_43',
				  'name' => 'ZA ochtend',
				  'type' => 'select',
				  'value' => '0',
				  'extra' => 
				  array (
				    'items' => '1|Ja
												0|Nee',
				    'multiple' => 0,
				    'title_display' => 'inline',
				    'private' => 0,
				    'wrapper_classes' => '',
				    'css_classes' => '',
				    'aslist' => 1,
				    'civicrm_live_options' => '1',
				    'optrand' => 0,
				    'other_option' => NULL,
				    'other_text' => 'Other...',
				    'description' => '',
				    'custom_keys' => false,
				    'options_source' => '',
				    'analysis' => true,
				  ),
				  'required' => '0',
				  'weight' => '25',
				  'page_num' => 1,
				),
				24 => 
				array (
				  'cid' => '24',
				  'pid' => '25',
				  'form_key' => 'civicrm_2_contact_1_relationship_custom_44',
				  'name' => 'ZA middag',
				  'type' => 'select',
				  'value' => '0',
				  'extra' => 
				  array (
				    'items' => '1|Ja
												0|Nee',
				    'multiple' => 0,
				    'title_display' => 'inline',
				    'private' => 0,
				    'wrapper_classes' => '',
				    'css_classes' => '',
				    'aslist' => 1,
				    'civicrm_live_options' => '1',
				    'optrand' => 0,
				    'other_option' => NULL,
				    'other_text' => 'Other...',
				    'description' => '',
				    'custom_keys' => false,
				    'options_source' => '',
				    'analysis' => true,
				  ),
				  'required' => '0',
				  'weight' => '26',
				  'page_num' => 1,
			),
			26 => 
				array (
				  'cid' => '26',
				  'pid' => '0',
				  'form_key' => 'beschikbaarheid_reserve',
				  'name' => 'Reserve beschikbaarheid',
				  'type' => 'fieldset',
				  'value' => '',
				  'extra' => 
				  array (
				    'private' => 0,
				    'css_classes' => '',
				    'title_display' => 0,
				    'collapsible' => 0,
				    'collapsed' => 0,
				    'description' => '',
				  ),
				  'required' => '0',
				  'weight' => '15',
				  'page_num' => 1,
				),
				27 => 
				array (
				  'cid' => '27',
				  'pid' => '26',
				  'form_key' => 'civicrm_2_contact_1_relationship_custom_45',
				  'name' => 'MA ochtend',
				  'type' => 'select',
				  'value' => '0',
				  'extra' => 
				  array (
				    'items' => '1|Ja
												0|Nee',
				    'multiple' => 0,
				    'title_display' => 'inline',
				    'private' => 0,
				    'wrapper_classes' => '',
				    'css_classes' => '',
				    'aslist' => 1,
				    'civicrm_live_options' => '1',
				    'optrand' => 0,
				    'other_option' => NULL,
				    'other_text' => 'Other...',
				    'description' => '',
				    'custom_keys' => false,
				    'options_source' => '',
				    'analysis' => true,
				  ),
				  'required' => '0',
				  'weight' => '15',
				  'page_num' => 1,
				),
				28 => 
				array (
				  'cid' => '28',
				  'pid' => '26',
				  'form_key' => 'civicrm_2_contact_1_relationship_custom_46',
				  'name' => 'MA middag',
				  'type' => 'select',
				  'value' => '0',
				  'extra' => 
				  array (
				    'items' => '1|Ja
												0|Nee',
				    'multiple' => 0,
				    'title_display' => 'inline',
				    'private' => 0,
				    'wrapper_classes' => '',
				    'css_classes' => '',
				    'aslist' => 1,
				    'civicrm_live_options' => '1',
				    'optrand' => 0,
				    'other_option' => NULL,
				    'other_text' => 'Other...',
				    'description' => '',
				    'custom_keys' => false,
				    'options_source' => '',
				    'analysis' => true,
				  ),
				  'required' => '0',
				  'weight' => '16',
				  'page_num' => 1,
				),
				29 => 
				array (
				  'cid' => '29',
				  'pid' => '26',
				  'form_key' => 'civicrm_2_contact_1_relationship_custom_47',
				  'name' => 'DI ochtend',
				  'type' => 'select',
				  'value' => '0',
				  'extra' => 
				  array (
				    'items' => '1|Ja
												0|Nee',
				    'multiple' => 0,
				    'title_display' => 'inline',
				    'private' => 0,
				    'wrapper_classes' => '',
				    'css_classes' => '',
				    'aslist' => 1,
				    'civicrm_live_options' => '1',
				    'optrand' => 0,
				    'other_option' => NULL,
				    'other_text' => 'Other...',
				    'description' => '',
				    'custom_keys' => false,
				    'options_source' => '',
				    'analysis' => true,
				  ),
				  'required' => '0',
				  'weight' => '17',
				  'page_num' => 1,
				),
				30 => 
				array (
				  'cid' => '30',
				  'pid' => '26',
				  'form_key' => 'civicrm_2_contact_1_relationship_custom_48',
				  'name' => 'DI middag',
				  'type' => 'select',
				  'value' => '0',
				  'extra' => 
				  array (
				    'items' => '1|Ja
												0|Nee',
				    'multiple' => 0,
				    'title_display' => 'inline',
				    'private' => 0,
				    'wrapper_classes' => '',
				    'css_classes' => '',
				    'aslist' => 1,
				    'civicrm_live_options' => '1',
				    'optrand' => 0,
				    'other_option' => NULL,
				    'other_text' => 'Other...',
				    'description' => '',
				    'custom_keys' => false,
				    'options_source' => '',
				    'analysis' => true,
				  ),
				  'required' => '0',
				  'weight' => '18',
				  'page_num' => 1,
				),
				31 => 
				array (
				  'cid' => '31',
				  'pid' => '26',
				  'form_key' => 'civicrm_2_contact_1_relationship_custom_49',
				  'name' => 'WO ochtend',
				  'type' => 'select',
				  'value' => '0',
				  'extra' => 
				  array (
				    'items' => '1|Ja
												0|Nee',
				    'multiple' => 0,
				    'title_display' => 'inline',
				    'private' => 0,
				    'wrapper_classes' => '',
				    'css_classes' => '',
				    'aslist' => 1,
				    'civicrm_live_options' => '1',
				    'optrand' => 0,
				    'other_option' => NULL,
				    'other_text' => 'Other...',
				    'description' => '',
				    'custom_keys' => false,
				    'options_source' => '',
				    'analysis' => true,
				  ),
				  'required' => '0',
				  'weight' => '19',
				  'page_num' => 1,
				),
				32 => 
				array (
				  'cid' => '32',
				  'pid' => '26',
				  'form_key' => 'civicrm_2_contact_1_relationship_custom_50',
				  'name' => 'WO middag',
				  'type' => 'select',
				  'value' => '0',
				  'extra' => 
				  array (
				    'items' => '1|Ja
												0|Nee',
				    'multiple' => 0,
				    'title_display' => 'inline',
				    'private' => 0,
				    'wrapper_classes' => '',
				    'css_classes' => '',
				    'aslist' => 1,
				    'civicrm_live_options' => '1',
				    'optrand' => 0,
				    'other_option' => NULL,
				    'other_text' => 'Other...',
				    'description' => '',
				    'custom_keys' => false,
				    'options_source' => '',
				    'analysis' => true,
				  ),
				  'required' => '0',
				  'weight' => '20',
				  'page_num' => 1,
				),
				33 => 
				array (
				  'cid' => '33',
				  'pid' => '26',
				  'form_key' => 'civicrm_2_contact_1_relationship_custom_51',
				  'name' => 'DO ochtend',
				  'type' => 'select',
				  'value' => '0',
				  'extra' => 
				  array (
				    'items' => '1|Ja
												0|Nee',
				    'multiple' => 0,
				    'title_display' => 'inline',
				    'private' => 0,
				    'wrapper_classes' => '',
				    'css_classes' => '',
				    'aslist' => 1,
				    'civicrm_live_options' => '1',
				    'optrand' => 0,
				    'other_option' => NULL,
				    'other_text' => 'Other...',
				    'description' => '',
				    'custom_keys' => false,
				    'options_source' => '',
				    'analysis' => true,
				  ),
				  'required' => '0',
				  'weight' => '21',
				  'page_num' => 1,
				),
				34 => 
				array (
				  'cid' => '34',
				  'pid' => '26',
				  'form_key' => 'civicrm_2_contact_1_relationship_custom_52',
				  'name' => 'DO middag',
				  'type' => 'select',
				  'value' => '0',
				  'extra' => 
				  array (
				    'items' => '1|Ja
												0|Nee',
				    'multiple' => 0,
				    'title_display' => 'inline',
				    'private' => 0,
				    'wrapper_classes' => '',
				    'css_classes' => '',
				    'aslist' => 1,
				    'civicrm_live_options' => '1',
				    'optrand' => 0,
				    'other_option' => NULL,
				    'other_text' => 'Other...',
				    'description' => '',
				    'custom_keys' => false,
				    'options_source' => '',
				    'analysis' => true,
				  ),
				  'required' => '0',
				  'weight' => '22',
				  'page_num' => 1,
				),
				35 => 
				array (
				  'cid' => '35',
				  'pid' => '26',
				  'form_key' => 'civicrm_2_contact_1_relationship_custom_53',
				  'name' => 'VR ochtend',
				  'type' => 'select',
				  'value' => '0',
				  'extra' => 
				  array (
				    'items' => '1|Ja
												0|Nee',
				    'multiple' => 0,
				    'title_display' => 'inline',
				    'private' => 0,
				    'wrapper_classes' => '',
				    'css_classes' => '',
				    'aslist' => 1,
				    'civicrm_live_options' => '1',
				    'optrand' => 0,
				    'other_option' => NULL,
				    'other_text' => 'Other...',
				    'description' => '',
				    'custom_keys' => false,
				    'options_source' => '',
				    'analysis' => true,
				  ),
				  'required' => '0',
				  'weight' => '23',
				  'page_num' => 1,
				),
				36 => 
				array (
				  'cid' => '36',
				  'pid' => '26',
				  'form_key' => 'civicrm_2_contact_1_relationship_custom_54',
				  'name' => 'VR middag',
				  'type' => 'select',
				  'value' => '0',
				  'extra' => 
				  array (
				    'items' => '1|Ja
												0|Nee',
				    'multiple' => 0,
				    'title_display' => 'inline',
				    'private' => 0,
				    'wrapper_classes' => '',
				    'css_classes' => '',
				    'aslist' => 1,
				    'civicrm_live_options' => '1',
				    'optrand' => 0,
				    'other_option' => NULL,
				    'other_text' => 'Other...',
				    'description' => '',
				    'custom_keys' => false,
				    'options_source' => '',
				    'analysis' => true,
				  ),
				  'required' => '0',
				  'weight' => '24',
				  'page_num' => 1,
				),
				37 => 
				array (
				  'cid' => '37',
				  'pid' => '26',
				  'form_key' => 'civicrm_2_contact_1_relationship_custom_55',
				  'name' => 'ZA ochtend',
				  'type' => 'select',
				  'value' => '0',
				  'extra' => 
				  array (
				    'items' => '1|Ja
												0|Nee',
				    'multiple' => 0,
				    'title_display' => 'inline',
				    'private' => 0,
				    'wrapper_classes' => '',
				    'css_classes' => '',
				    'aslist' => 1,
				    'civicrm_live_options' => '1',
				    'optrand' => 0,
				    'other_option' => NULL,
				    'other_text' => 'Other...',
				    'description' => '',
				    'custom_keys' => false,
				    'options_source' => '',
				    'analysis' => true,
				  ),
				  'required' => '0',
				  'weight' => '25',
				  'page_num' => 1,
				),
				38 => 
				array (
				  'cid' => '38',
				  'pid' => '26',
				  'form_key' => 'civicrm_2_contact_1_relationship_custom_56',
				  'name' => 'ZA middag',
				  'type' => 'select',
				  'value' => '0',
				  'extra' => 
				  array (
				    'items' => '1|Ja
												0|Nee',
				    'multiple' => 0,
				    'title_display' => 'inline',
				    'private' => 0,
				    'wrapper_classes' => '',
				    'css_classes' => '',
				    'aslist' => 1,
				    'civicrm_live_options' => '1',
				    'optrand' => 0,
				    'other_option' => NULL,
				    'other_text' => 'Other...',
				    'description' => '',
				    'custom_keys' => false,
				    'options_source' => '',
				    'analysis' => true,
				  ),
				  'required' => '0',
				  'weight' => '26',
				  'page_num' => 1,
			),
	);

	$node->webform = array(
		'confirmation' => '',
		'confirmation_format' => 'plain_text',
		'redirect_url' => '/volunteers',
		'status' => '1',
		'block' => '0',
		'allow_draft' => '0',
		'auto_save' => '0',
		'submit_notice' => '0',
		'submit_text' => 'Save',
		'submit_limit' => '-1',
		'submit_interval' => '-1',
		'total_submit_limit' => '-1',
		'total_submit_interval' => '-1',
		'progressbar_bar' => '0',
		'progressbar_page_number' => '0',
		'progressbar_percent' => '0',
		'progressbar_pagebreak_labels' => '0',
		'progressbar_include_confirmation' => '1',
		'progressbar_label_first' => 'Start',
		'progressbar_label_confirmation' => 'Complete',
		'record_exists' => true,
		'roles' => 
		array (
		  0 => '3',
			1 => '5',
		),
		'emails' => array(),
		'components' => $components,
	);


	$webform_civicrm_data = array (
		'contact' => array (
			1 => array (
				'contact' => array(
					1 => array (
						'contact_type' => 'individual',
						'contact_sub_type' => array(
							'Volunteer' => 'Volunteer'
						),
						'webform_label' => 'Volunteer',
					),
				),
				'number_of_cg1' => 1,
				'number_of_other' => 0,
				'number_of_address' => 1,
				'number_of_phone' => 1,
				'number_of_email' => 1,
				'number_of_website' => 0,
				'address' => array (
					1 => array(
						'location_type_id' => 1,
					)
				),
				'phone' => array (
					1 => array(
						'phone_type_id' => 1,
						'location_type_id' => 1
					)
				),
				'email' => array(
					1 => array (
						'location_type_id' => 1
					)
				)
			),
			2 => array (
				'contact' => array (
					1 => array (
						'contact_type' => 'organization',
						'contact_sub_type' => array (),
						'webform_label' => 'Shop'
					)
				),
				'number_of_other' => 0,
				'number_of_address' => 0,
				'number_of_phone' => 0,
				'number_of_email' => 0,
				'number_of_website' => 0,
				'number_of_relationship' => 1,
				'relationship' => array (
					1 => array(
						'relationship_type_id' => array (
							'5_b' => '5_b'
						),
						'is_active' => 1
					)
				)
			)
		),
		'membership' => array( 
			1 => array ( 'number_of_membership' => 0 ),
			2 => array ( 'number_of_membership' => 0 ),
		),
		'participant_reg_type' => 0,
		'reg_options' => array (
			'event_type' => 'any',
			'show_past_events' => 0,
			'title_display' => 'title',
			'show_remaining' => 0,
			'validate' => 1,
			'block_form' => 0,
		)
	);

	$node->path = array('alias' => 'volunteers/edit');
	// Save the node.
	node_save($node);

	$node_id = $node->nid;
	variable_set('oxfam_volunteer_webform_node_id', $node_id);

	//set civicrm settings
	$civicrm_settings = new stdClass();
	$civicrm_settings->nid = $node_id;
	$civicrm_settings->data = $webform_civicrm_data;
	$civicrm_settings->prefix_known = '';
	$civicrm_settings->prefix_unknown = '';
	$civicrm_settings->message = '';
	$civicrm_settings->confirm_subscription = 1;
	$civicrm_settings->block_unknown_users = 1;
	$civicrm_settings->create_fieldsets = 0;
	$civicrm_settings->new_contact_source = 'Shop manager';
	drupal_write_record('webform_civicrm_forms', $civicrm_settings);
}

/**
 * Implements hook_views_default_views().
 */
function oxfam_volunteer_views_default_views() {
	$views = array();
	require('views/views_volunteers_reserve.inc');
	require('views/views_volunteers_availability.inc');
	require('views/views_volunteers.inc');
// return views
  return $views;
}
